<div class="navigation"> <!--Left Navigation-->
			<!--#include virtual="menu.inc"-->
				<h3>
	</h3>
	
	<h3>Assignments</h3>
	<ul>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Assignment1">Assignment 1 </a></li>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Assignment2">Assignment 2 </a></li>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Assignment3">Assignment 3 </a></li>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Assignment4">Assignment 4 </a></li>
	</ul>
	<h3>Lab Practica</h3>
	<ul>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Practium1">Practicum 1</a></li>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Practium2">Practicum 2</a></li>
	</ul>
		</div> <!--Left Navigation Closing-->
		
		<div class="allcontent"> <!--Other part other than navigation-->
			
			<div class="header"> <!--Header-->
			
				
				<!--#include virtual="header.inc"-->
								<div class="leftheader"> <!-- Left Header-->
					<p>
					</p><div class="headingfont">IT 207-DL3 Fall 2021 </div>
					Daniel Garrison <br>
					George Mason university
					<br>
										<p></p>
				
				</div> <!--Left Header Closing-->
				
				<div class="rightheader"> <!--Right Header-->
				
					<p>
					</p><div class="headingfont">Cayden Taylor</div>
					<a href="mailto:ctaylo50@gmu.edu">ctaylo50@gmu.edu</a><br>
					Today's Date:...

					<br>
														
										<p></p>
				
				</div> <!--Right Header Closing-->
				
			</div> <!--Header closing-->