<div class="navigation"> <!--Left Navigation-->
			<!--#include virtual="menu.inc"-->
				<h3>
	</h3>
	<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/">Home </a></li>
	<h3>Assignments</h3>
	<ul>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Assignment1/Lab1.php">Assignment 1 </a></li>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Assignment2/OfficeHoursSetup.php">Assignment 2 </a></li>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Assignment3">Assignment 3 </a></li>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Assignment4">Assignment 4 </a></li>
	</ul>
	<h3>Lab Practica</h3>
	<ul>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Practium1">Practicum 1</a></li>
		<li><a href="http://helios.ite.gmu.edu/~ctaylo50/IT207/Practium2">Practicum 2</a></li>
	</ul>
		</div> <!--Left Navigation Closing-->