<div class="allcontent"> <!--Other part other than navigation-->
<div class="header"> <!--Header-->
			
				
				<!--#include virtual="header.inc"-->
								<div class="leftheader"> <!-- Left Header-->
					<p>
					</p><div class="headingfont">
					IT 207-DL3 Fall 2021 </div>
					Daniel Garrison<br>
					George Mason university
					<br>
										<p></p>
				
				</div> <!--Left Header Closing-->
				
				<div class="rightheader"> <!--Right Header-->
				
					<p>
					</p><div class="headingfont"><?php
					echo "Cayden Taylor";
					?></div>
					<a href="mailto:ctaylo50@gmu.edu">ctaylo50@gmu.edu</a><br>
					<?php
						date_default_timezone_set('EST');
						date_default_timezone_set('America/New_York');
						echo date("l jS \of F Y h:i:s A");
					
					?>

					<br>
														
										<p></p>
				
				</div> <!--Right Header Closing-->
				
			</div> <!--Header closing-->